version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "dev"
    reviewers:
      - "justedlev"
    assignees:
      - "justedlev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    reviewers:
      - "justedlev"
    assignees:
      - "justedlev"
    schedule:
      interval: "weekly"
