spring:
  security:
    oauth2:
      client:
        enabled: true
        provider:
          keycloak:
            issuer-uri: ${KC_ISSUER_URI}
            user-name-attribute: preferred_username
            user-info-authentication-method: header
        registration:
          default: &default_client_registration
            provider: keycloak
            client-name: "BridgeWay Hub"
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            scope:
              - openid
              - microprofile-jwt
              - discovery:rw
          client-credentials:
            <<: *default_client_registration
            authorization-grant-type: client_credentials
            scope:
              - discovery:rw
      resourceserver:
        enabled: true
        jwt:
          issuer-uri: ${KC_ISSUER_URI}
bridgeway:
  security:
    whitelist:
      GET:
        - /webjars/**
        - /v3/api-docs/**
        - /swagger-ui.html
        - /swagger-ui/**
        - /swagger-resources
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /actuator/**
        - /error
      POST:
        - /sso/logout
        - /logout
