blank_issues_enabled: true
contact_links:
  - name: â“ Ask a question or get help
    url: https://github.com/justedlev/spring-boot-template/discussions
    about: Use GitHub Discussions for general questions and help.

  - name: ğŸ› Report a security vulnerability
    url: https://github.com/justedlev/spring-boot-template/security
    about: Please report security issues privately here.
